### ISSUE TITLE
Run Main.m failed!

### ISSUE THREAD

**Issue by 5by2by1by** [MoranHansir/BWS_Exoskeleton#1]
My environment: Win 10, opensim 4.0,  matlab 2017b
 When I run without any modifications, i came into an error:

"Java exception occurred: 
java.io.IOException: Failed to connect Socket 'child_frame' of type PhysicalFrame (details: Component 'ground_pelvis' could not find '../pelvis' of type PhysicalFrame. Make sure a component exists at this path and that it is of the correct type.
	Thrown at component.h:764 in getComponent().).
	In Object 'ground_pelvis' of type CustomJoint.
	Thrown at component.cpp:312 in finalizeConnections().

	at org.opensim.modeling.opensimSimulationJNI.Model_initSystem(Native Method)

	at org.opensim.modeling.Model.initSystem(Model.java:848)"

i am new to opensim and quite interested in your repo, thanks for answering!

**Comment by MoranHansir** [comment]
你好。最近很忙暂时不能帮你详细排查原因，很抱歉。根据你的描述我认为出现报错的原因可能是未将程序所在的文件路径添加到计算机系统环境变量的path中。另外建议运行一下opensim中自带的matlab联合仿真例程来检查一下软件是否配置完善。发自我的荣耀手机-------- 原始邮件 --------发件人： 5by2by1by ***@***.***>日期： 2021年4月20日周二 下午2:40收件人： MoranHansir/BWS_Exoskeleton ***@***.***>抄送： Subscribed ***@***.***>主    题： [MoranHansir/BWS_Exoskeleton] Run Main.m failed! (#1)
My environment: Win 10, opensim 4.0,  matlab 2017b
When I run without any modifications, i came into an error:
"Java exception occurred:
java.io.IOException: Failed to connect Socket 'child_frame' of type PhysicalFrame (details: Component 'ground_pelvis' could not find '../pelvis' of type PhysicalFrame. Make sure a component exists at this path and that it is of the correct type.
Thrown at component.h:764 in getComponent().).
In Object 'ground_pelvis' of type CustomJoint.
Thrown at component.cpp:312 in finalizeConnections().
at org.opensim.modeling.opensimSimulationJNI.Model_initSystem(Native Method)

at org.opensim.modeling.Model.initSystem(Model.java:848)"

i am new to opensim and quite interested in your repo, thanks for answering!

**Comment by MoranHansir** [comment]
你好，刚看了下，我这边程序运行没报错，matlab版本需要2019a才行。这个联合仿真的版本后续我没维护，仿真速度太慢，我现在的版本是把opensim里的人体几何模型导入到了matlab中，全部用的simulink来仿真，但没有肌肉模型。这个新版本内容还没发表，如果你需要参考的话可以发你邮箱。但是目前遇到的问题还是无法大幅度提高仿真速度，初步认为原因在于动力学引擎不能很好的处理多体系统。Matlab在电脑上可以安装多个版本，你试一下2019a或最新的。最近在写博士论文所以时间比较紧张，如果切换版本后还是有问题可以电话沟通，方便一些:吴寒，15073193804，微信同手机号。发自我的荣耀手机-------- 原始邮件 --------发件人： Reha-Robot ***@***.***>日期： 2021年4月24日周六 下午1:31收件人： MoranHansir/BWS_Exoskeleton ***@***.***>抄送： MoranHansir ***@***.***>, Comment ***@***.***>主    题： Re: [MoranHansir/BWS_Exoskeleton] Run Main.m failed! (#1)
hello，已经运行Opensim配置检查，Matlab输出4.1，配置正确。.osim文件打开提示添加的文件中不少报错，我想您可能上传错了文件。请问您有最新版的正确文件提供参考吗，不胜感激。我们是自发建立的一个Opensim学习小组，目前有很多人都在参考您的案例。

**Comment by MoranHansir** [comment]
我电脑上的源代码无法直接发送该邮箱，如有需要请留个人邮箱地址。




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "MoranHansir/BWS_Exoskeleton"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月24日(星期六) 中午1:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MoranHansir/BWS_Exoskeleton] Run Main.m failed! (#1)





 
hello，已经运行Opensim配置检查，Matlab输出4.1，配置正确。.osim文件打开提示添加的文件中不少报错，我想您可能上传错了文件。请问您有最新版的正确文件提供参考吗，不胜感激。我们是自发建立的一个Opensim学习小组，目前有很多人都在参考您的案例。

**Comment by MoranHansir** [comment]
Git把你邮箱屏蔽了哦发自我的荣耀手机-------- 原始邮件 --------发件人： Reha-Robot ***@***.***>日期： 2021年4月24日周六 下午2:44收件人： MoranHansir/BWS_Exoskeleton ***@***.***>抄送： MoranHansir ***@***.***>, Comment ***@***.***>主    题： Re: [MoranHansir/BWS_Exoskeleton] Run Main.m failed! (#1)
***@***.***，谢谢谢谢









------------------&nbsp;原始邮件&nbsp;------------------

发件人: ***@***.***&gt;; 

发送时间: 2021年4月24日(星期六) 下午2:42

收件人: ***@***.***&gt;; 

抄送: ***@***.***&gt;; ***@***.***&gt;; 

主题: Re: [MoranHansir/BWS_Exoskeleton] Run Main.m failed! (#1)











 我电脑上的源代码无法直接发送该邮箱，如有需要请留个人邮箱地址。 

 

 

 

 

 ------------------ 原始邮件 ------------------ 

 发件人:                                                                                                                        "MoranHansir/BWS_Exoskeleton"                                                                                    ***@***.***&amp;gt;; 

 发送时间:&amp;nbsp;2021年4月24日(星期六) 中午1:31 

 ***@***.***&amp;gt;; 

 ***@***.******@***.***&amp;gt;; 

 主题:&amp;nbsp;Re: [MoranHansir/BWS_Exoskeleton] Run Main.m failed! (#1) 

 

 

 

 

 

   

 hello，已经运行Opensim配置检查，Matlab输出4.1，配置正确。.osim文件打开提示添加的文件中不少报错，我想您可能上传错了文件。请问您有最新版的正确文件提供参考吗，不胜感激。我们是自发建立的一个Opensim学习小组，目前有很多人都在参考您的案例。
